### PR TITLE
Feat/tap 2885

### PR DESCRIPTION
**Pull request by xbsura**

### CODE REVIEW

**Review by ply0011 — APPROVED** [review]

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **37.5**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **10.526315789473685**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **37.5**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **10.526315789473685**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **37.5**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **10.526315789473685**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.92307692307692**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **39.285714285714285**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.77777777777777**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **22.727272727272727**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **29.166666666666668**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=feat/TAP-2885&id=tapdata

**Pull request merged**
