### PR TITLE
TAP-5061:fix cloud Permission RoleMapping Large flow

### PR DESCRIPTION
**Pull request by weiliang110100**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5061-fix_cloud_Permission_RoleMapping_Large_flow&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5061-fix_cloud_Permission_RoleMapping_Large_flow&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5061-fix_cloud_Permission_RoleMapping_Large_flow&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5061-fix_cloud_Permission_RoleMapping_Large_flow&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
