### PR TITLE
add retry status for milestone

### PR DESCRIPTION
**Pull request by openlg**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **38.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **59.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **65.6**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **65.6**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **21.35922**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **21.92691**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **21.92691**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **21.92691**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5092-milestone-optimization&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
