### PR TITLE
TAP-4927:fix(iengine):cloud merge task appear error when target use n…

### PR DESCRIPTION
**Pull request by ljvv7**
…o passwod mongo

### CODE REVIEW

**Review by ply0011 — APPROVED** [review]

**Review by ply0011 — CHANGES_REQUESTED** [review]
最好能复用已有的工具方法

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **57.1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4927-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **57.1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4927-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4927-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4927-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4927-dev&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
