### PR TITLE
feat: TAP-3358 multi thread table reading when doing data replica

### PR DESCRIPTION
**Pull request by mnianqi**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.545454545454545**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3358&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.545454545454545**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3358&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.417040358744394**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3358&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.41704**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3358&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3358&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
