### PR TITLE
Tap 4533 Metrics optimization

### PR DESCRIPTION
**Pull request by ply0011**
Ensure Total Input Matches Total Output

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **73.6**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4533&id=tapdata

**Review by jackin-code — APPROVED** [review]

**Pull request merged**
