### PR TITLE
Tap 3657 7586 v3.8.0 send email failed

### PR DESCRIPTION
**Pull request by 11000100111010101100111**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_security_rating**, ActualValue: **4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **40.56604**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3657-7586-V3.8.0-send-email-failed&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_security_rating**, ActualValue: **4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **40.56604**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3657-7586-V3.8.0-send-email-failed&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **32.5**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3657-7586-V3.8.0-send-email-failed&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **5.16129**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3657-7586-V3.8.0-send-email-failed&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **6.15385**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3657-7586-V3.8.0-send-email-failed&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Comment by ply0011** [comment]
## Exception case
Merging into the release branch does not require a Sonar scan, starting from release-v3.10.0

**Pull request merged**
