### PR TITLE
Tap-5090 update errorCode

### PR DESCRIPTION
**Pull request by ljvv7**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **13.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **13.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **13.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **13.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **61.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **67.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **67.9**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5090-dev&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
