### PR TITLE
fix(MongoDB): TAP-2427 mongodb open 'Incremental multi-threaded write…

### PR DESCRIPTION
**Pull request by HarsenLin**
…' heartbeat can't propel offset.

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2427-develop-mongoOffsetCantPropel&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2427-develop-mongoOffsetCantPropel&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2427-develop-mongoOffsetCantPropel&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2427-develop-mongoOffsetCantPropel&id=tapdata

**Comment by ply0011** [comment]
Exception Handling
1. Merged from the old version after fixing and testing
2. The changes are minor, but the methods involved in testing are too long
So this pull request requires mandatory test coverage.

**Review by ply0011 — APPROVED** [review]

**Review by jackin-code — APPROVED** [review]

**Pull request merged**
