### PR TITLE
Fix upload pdk v3.11.0

### PR DESCRIPTION
**Pull request by openlg**

### CODE REVIEW

**Review by ply0011 — APPROVED** [review]

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **21.3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-upload-pdk-v3.11.0&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **34.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-upload-pdk-v3.11.0&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **48.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-upload-pdk-v3.11.0&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **75.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-upload-pdk-v3.11.0&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **76.2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-upload-pdk-v3.11.0&id=tapdata

**Pull request merged**
