### PR TITLE
Feat Tap-3684 Add 'Kafka-Enhanced' connector

### PR DESCRIPTION
**Pull request by HarsenLin**
Feat Tap-3684 Add 'Kafka-Enhanced' connector

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **66.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-3684-develop-stdkafka&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **69.2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-3684-develop-stdkafka&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **71.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-3684-develop-stdkafka&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **71.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=harsen/TAP-3684-develop-stdkafka&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
