### PR TITLE
Merge develop into main

### PR DESCRIPTION
**Pull request by ply0011**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.28285077951003**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **33**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **14**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=develop&id=tapdata

**Comment by ply0011** [comment]
# Exception case
Bugs and test corverage all caused by the analyze resource feature, author: xbsure. No impact on other functionality. When merging, we agrees that Sonar conclusions can be ignored.
  - https://github.com/tapdata/tapdata/pull/1975
  - https://github.com/tapdata/tapdata/pull/1996
  - https://github.com/tapdata/tapdata/pull/1997

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.28285077951003**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **33**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **13**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=develop&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.93791574279379**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **33**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **13**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=develop&id=tapdata

**Pull request merged**
