### PR TITLE
Tap 2953 heart beat mongo

### PR DESCRIPTION
**Pull request by ljvv7**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **79.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2953-heartBeatMongo&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
