### PR TITLE
fix: TAP-3457 #7495 【V3.6.0】数据转换，mysql-->mongodb,追加合并，报错：Unable to wr…

### PR DESCRIPTION
**Pull request by mnianqi**
…ite data to mongodb due to violationof unique constraint.

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **4.545454545454546**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **4.545454545454546**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **4.545454545454546**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3457-7495-violationof-unique-constraint&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
