### PR TITLE
TAP-3383 feat(tm): The LDP supports display of all models in the mdm library

### PR DESCRIPTION
**Pull request by ply0011**
Closes TAP-3383

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.0**
- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3383&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3383&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3383&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3383&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3383&id=tapdata

**Comment by ply0011** [comment]
# Exception case
one issue is not from new code

**Review by jackin-code — APPROVED** [review]

**Comment by jackin-code** [comment]
exception case

**Pull request merged**
