### PR TITLE
feat: TAP-4583 snapshot stage should display all tables status in mig…

### PR DESCRIPTION
**Pull request by mnianqi**
…rate task

### CODE REVIEW

**Review by ply0011 — CHANGES_REQUESTED** [review]
1. doCount已经弃用了，建议考虑换成新的doAsyncTableCount
2. 可以考虑，先将表名列表同步的上报，后续异步的将count结果更新

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **70.4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **26.76056**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4583&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4583&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4583&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.7**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4583&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
