### PR TITLE
fix(TM): TAP-116 TASK Warning alert format

### PR DESCRIPTION
**Pull request by ljvv7**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-116-develop-alarmInfo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-116-develop-alarmInfo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **1**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-116-develop-alarmInfo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **75.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-116-develop-alarmInfo&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **75.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-116-develop-alarmInfo&id=tapdata

**Review by ply0011 — CHANGES_REQUESTED** [review]
为什么把userDetail删了

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
