### PR TITLE
Tap-4682-oem-log

### PR DESCRIPTION
**Pull request by ljvv7**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **28.4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.70464**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **28.4**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **9.74576**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **45.8**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **11.12676**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **45.8**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **11.12676**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **45.8**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **11.09551**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **45.8**
- Status: **ERROR**, MetricKey: **new_duplicated_lines_density**, ActualValue: **11.09551**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4682-dev&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
