### PR TITLE
TAP-2405 fix metrics miss

### PR DESCRIPTION
**Pull request by ningmeng777**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2405-FIX-metrics-miss-when-task-complete&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2405-FIX-metrics-miss-when-task-complete&id=tapdata

**Review by ply0011 — CHANGES_REQUESTED** [review]
1. 线程增加名字
2. 增加单测，多线程测试
3. 增加异常处理，不抛出错误，打印info级别日志

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.10650887573965**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2405-FIX-metrics-miss-when-task-complete&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.10650887573965**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-2405-FIX-metrics-miss-when-task-complete&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
