### PR TITLE
Fix dev tap-3819 thread group leaked

### PR DESCRIPTION
**Pull request by ljvv7**

### CODE REVIEW

**Review by ply0011 — CHANGES_REQUESTED** [review]
需要复用thread group来防止泄漏

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-dev-TAP-3819&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-dev-TAP-3819&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=fix-dev-TAP-3819&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
