### PR TITLE
Tap 4842 Task preview

### PR DESCRIPTION
**Pull request by ply0011**

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **7.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **5.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **9.6**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **10.0**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **11.2**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **68.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **68.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **68.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **68.8**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **72.6**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **72.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **72.4**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4842&id=tapdata

**Comment by jackin-code** [comment]
exception case: most of main logic cover unit test.

**Review by jackin-code — APPROVED** [review]

**Pull request merged**
