### PR TITLE
feat: TAP-3982 whether create unique index according to update condit…

### PR DESCRIPTION
**Pull request by mnianqi**
…ion fileds

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3982-main-unique-index&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3982-main-unique-index&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_critical_violations**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_major_violations**, ActualValue: **2**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3982-main-unique-index&id=tapdata

**Review by ply0011 — APPROVED** [review]
## Exception case

Sonar issues not from new code, ignore it

**Pull request merged**
