### PR TITLE
fix(iengine): TAP-4266 T-100.9: dummy -> dummy, 1KB record, empty rename

### PR DESCRIPTION
**Pull request by ply0011**
Closes TAP-4266

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_reliability_rating**, ActualValue: **3**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **60.16260162601626**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4266&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **79.13669064748201**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4266&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **79.13669064748201**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4266&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **79.13669064748201**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4266&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **78.57142857142857**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-4266&id=tapdata

**Comment by ply0011** [comment]
## Exception case

The remaining lines of code have little significance for unit testing, and it's acceptable if they do not reach 80% coverage

**Review by jackin-code — APPROVED** [review]

**Pull request merged**
