### PR TITLE
fix: TAP-5143 There are field names A and B, if field A->B and field …

### PR DESCRIPTION
**Pull request by mnianqi**
…B->C, the model deduction will lose field B

### CODE REVIEW

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5143&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **3**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5143&id=tapdata

**Review by ply0011 — CHANGES_REQUESTED** [review]
需要考虑性能，去掉uuid的调用，初始化时先缓存好信息

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5143&id=tapdata

**Comment by xbsura** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_maintainability_rating**, ActualValue: **2**
- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **77.8**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-5143&id=tapdata

**Review by ply0011 — APPROVED** [review]

**Pull request merged**
